version: '3'

services:
    sattrak_db:
        image: postgres:12.1-alpine
        container_name: sattrak_db
        volumes:
            - ./docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
        environment:
            - POSTGRES_DB=sattrak_db
            - POSTGRES_USER=sattrak_db_user
            - POSTGRES_PASSWORD=44rp1JKJ7m9FEJyg
        ports:
            - 8032:5432

    sattrak_php:
        build: docker/php
        container_name: sattrak_php
        restart: always
        tty: true
        volumes:
          - .:/srv/sattrak:delegated